DELETE http://localhost:3003/api/blogs/61d7356192e59f136e98f84c
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYxZDcyZjI1M2Y1MTRhMmRkYmIxZDdiNyIsImlhdCI6MTY0MTQ5NDI3NH0.OtTQIQ_05_x5GJCcSFd8ZYe2vwwlNwHp0Uwr4bs_ZAc