PUT http://localhost:3003/api/blogs/5a422bc61b54a676234d17fc
Content-Type: application/json

{
  "title": "Fourth post",
  "author": "Agapito Perez",
  "url": "http://blospot.com/agapito-adventures/post-4",
  "likes": 7
}